version: '3.4'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - fmatheus-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - fmatheus-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    networks:
      - fmatheus-network
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  rabbitmq:
    image: rabbitmq:3.11.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672" #AMQP protocol port
      - "15672:15672" #HTTP management UI
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - fmatheus-network

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin-server
    hostname: zipkin-server
    restart: always
    ports:
      - "9411:9411"
    depends_on:
      - rabbitmq
      - kafka
      - zookeeper
      - kafdrop
    environment:
      RABBIT_URI: amqp://admin:admin@rabbitmq:5672
    networks:
      - fmatheus-network

  cambium-db:
    image: mysql:8.0.29
    container_name: cambium-db
    hostname: cambium-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambium_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - fmatheus-network

  book-db:
    image: mysql:8.0.29
    container_name: book-db
    hostname: book-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - "3310:3310"
    expose:
      - 3310
    networks:
      - fmatheus-network

  naming-server:
    image: fmatheus21/naming-server
    container_name: naming-server
    hostname: naming-server
    restart: always
    build:
      context: .
      dockerfile: naming-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - fmatheus-network

  api-gateway:
    image: fmatheus21/api-gateway
    container_name: api-gateway
    hostname: api-gateway
    restart: always
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - rabbitmq
      - kafka
      - zookeeper
      - kafdrop
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://bookstore:yt76Tdn93@naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://admin:admin@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - fmatheus-network

  cambium-service:
    image: fmatheus21/cambium-service
    container_name: cambium-service
    hostname: cambium-service
    restart: always
    build:
      context: .
      dockerfile: cambium-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://bookstore:yt76Tdn93@naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://admin:admin@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.APPLICATION.NAME: cambium-service
      SPRING.DATASOURCE.URL: jdbc:mysql://cambium-db:3308/cambium_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambium-db:3308/cambium_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: admin123
      KAFKA_HOST: kafka29092
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - cambium-db
      - api-gateway
      - rabbitmq
      - kafka
      - zookeeper
      - kafdrop
    networks:
      - fmatheus-network

  book-service:
    image: fmatheus21/book-service
    container_name: book-service
    hostname: book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://bookstore:yt76Tdn93@naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://admin:admin@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.APPLICATION.NAME: book-service
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: admin123
      KAFKA_HOST: kafka29092
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - book-db
      - rabbitmq
      - kafka
      - zookeeper
      - kafdrop
      - cambium-service
    networks:
      - fmatheus-network

networks:
  fmatheus-network:
    driver: bridge