version: '3.4'

services:

  config-server:
    image: fmatheus21/config-server
    restart: always
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - 8888:8888
    networks:
      - fmatheus-network

  naming-server:
    image: fmatheus21/naming-server
    restart: always
    build:
      context: .
      dockerfile: naming-server/Dockerfile
    ports:
      - 8761:8761
    depends_on:
      - config-server
    networks:
      - fmatheus-network

networks:
  fmatheus-network:
    driver: bridge