version: '3.4'

services:

  config-server:
    image: fmatheus21/bookstore_config-server
    restart: always
    environment:
      GIT_PASSWORD: ${GIT_PASSWORD}
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - 8888:8888
    networks:
      - fmatheus-network

  rabbit-mq:
    image: fmatheus21/rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - fmatheus-network

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    restart: always
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - fmatheus-network

  bookstore-cambium-db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambium_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - fmatheus-network

  bookstore-book-db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3310
    expose:
      - 3310
    networks:
      - fmatheus-network

  naming-server:
    image: fmatheus21/bookstore_naming-server
    restart: always
    build:
      context: .
      dockerfile: naming-server/Dockerfile
    ports:
      - 8761:8761
    depends_on:
      - config-server
    networks:
      - fmatheus-network

  api-gateway:
    image: fmatheus21/bookstore_api-gateway
    restart: always
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - 8765:8765
    depends_on:
      - config-server
      - naming-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - fmatheus-network

  cambium-service:
    image: fmatheus21/bookstore_cambium-service
    restart: always
    build:
      context: .
      dockerfile: cambium-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.APPLICATION.NAME: cambium-service
      SPRING.DATASOURCE.URL: jdbc:mysql://bookstore-cambium-db:3308/cambium_service?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://bookstore-cambium-db:3308/cambium_service?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: admin123
    ports:
      - 8000:8000
    depends_on:
      - config-server
      - naming-server
      - bookstore-cambium-db
      - rabbit-mq
    networks:
      - fmatheus-network

  book-service:
    image: fmatheus21/bookstore_book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.APPLICATION.NAME: book-service
      SPRING.DATASOURCE.URL: jdbc:mysql://bookstore-book-db:3310/book_service?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://bookstore-book-db:3310/book_service?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: admin123
    ports:
      - 8100:8100
    depends_on:
      - config-server
      - naming-server
      - bookstore-book-db
      - rabbit-mq
    networks:
      - fmatheus-network

networks:
  fmatheus-network:
    driver: bridge