server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: ${BRANCH:main}
          ignore-local-ssh-settings: true
          password: ${GIT_PASSWORD}
          search-paths: 'bookstore/{application}'
          uri: ${GIT_URI:https://github.com/fmatheus21/config-server-git}
          username: ${GIT_USERNAME:fmatheus21}